// =============================================
//  SAHAY — SAMPLE DATA
// =============================================

export const JOBS = [
  {
    id: '1',
    role: 'Junior Software Developer',
    company: 'TechCorp India',
    location: 'Bengaluru',
    salary: '4–6 LPA',
    type: 'Full-time',
    mode: 'Hybrid',
    verified: true,
    accommodation: true,
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=techcorp&backgroundColor=e6f3f3',
    description: `We are looking for a junior developer to join our inclusive team. You'll work on building scalable web applications using React and Node.js. We have a fully accessible office with assistive technology setups, flexible working hours, and a sign language interpreter available for team meetings.`,
    requirements: ['B.Tech / BCA in CS or related', '0–2 years experience', 'React or Vue knowledge', 'Good communication skills'],
    accessibility: {
      workplace: 'Fully wheelchair accessible office, accessible restrooms on every floor',
      remote: 'Hybrid — 3 days from home, 2 in office',
      assistiveTech: 'Screen reader compatible workstation, standing desk available',
      interview: 'Video interview available, sign language interpreter on request, extended time',
    },
    interview: 'Two rounds: technical screen (30 min video) + culture fit (45 min). Accessible format on request.',
    postedDays: 2,
  },
  {
    id: '2',
    role: 'Customer Support Associate',
    company: 'Zomato',
    location: 'Remote',
    salary: '2.5–3.5 LPA',
    type: 'Full-time',
    mode: 'Remote',
    verified: true,
    accommodation: true,
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=zomato&backgroundColor=fef3e2',
    description: 'Join our customer excellence team and help millions of customers with their orders. Fully remote role with flexible shifts. We welcome candidates with hearing disabilities — written communication tools available.',
    requirements: ['12th pass or above', 'Good written English', 'Customer-service mindset', 'Reliable internet connection'],
    accessibility: {
      workplace: 'Fully remote — work from anywhere in India',
      remote: 'Remote-first, asynchronous communication supported',
      assistiveTech: 'Text-based communication tools, no phone calls required for this role',
      interview: 'Written interview option available, no audio required',
    },
    interview: 'Online written assessment + async video/text interview.',
    postedDays: 5,
  },
  {
    id: '3',
    role: 'Graphic Designer',
    company: 'Ogilvy India',
    location: 'Mumbai',
    salary: '4–7 LPA',
    type: 'Full-time',
    mode: 'On-site',
    verified: false,
    accommodation: false,
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=ogilvy&backgroundColor=f0fafa',
    description: 'Creative graphic designer for our brand team. Work on exciting campaigns for top brands.',
    requirements: ['Degree in design', '2+ years experience', 'Proficiency in Adobe Suite', 'Strong portfolio'],
    accessibility: {
      workplace: 'Office accessibility being upgraded — ramp and accessible lift available',
      remote: 'On-site primarily, WFH Fridays',
      assistiveTech: 'Not specified — contact HR',
      interview: 'In-person interview at accessible venue',
    },
    interview: 'Portfolio review + creative brief presentation.',
    postedDays: 7,
  },
  {
    id: '4',
    role: 'Data Entry Operator (Govt. Quota)',
    company: 'UIDAI',
    location: 'Delhi',
    salary: '2–3 LPA',
    type: 'Contract',
    mode: 'On-site',
    verified: true,
    accommodation: true,
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=uidai&backgroundColor=e6f6ee',
    description: 'Government post under disability reservation quota. Stable, structured work with full accommodation support.',
    requirements: ['10th pass', 'Typing speed 30 WPM', 'UDID card required', 'Local resident preferred'],
    accessibility: {
      workplace: 'Government building — fully accessible per RPWD Act 2016',
      remote: 'On-site',
      assistiveTech: 'Screen-reader workstations available',
      interview: 'Extended time granted, scribe available on request',
    },
    interview: 'Written test + document verification.',
    postedDays: 1,
  },
  {
    id: '5',
    role: 'Content Writer',
    company: 'Byju\'s',
    location: 'Remote',
    salary: '3–5 LPA',
    type: 'Part-time',
    mode: 'Remote',
    verified: false,
    accommodation: false,
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=byjus&backgroundColor=fef7e0',
    description: 'Create engaging educational content for students across India. Fully remote, flexible hours.',
    requirements: ['Strong writing skills', 'Subject matter expertise (any)', 'Ability to simplify complex topics'],
    accessibility: {
      workplace: 'Remote',
      remote: 'Fully remote, asynchronous',
      assistiveTech: 'Not specified',
      interview: 'Written assignment',
    },
    interview: 'Submit a sample article + short HR call.',
    postedDays: 3,
  },
];

export const APPLICATIONS = [
  {
    id: 'app-1',
    jobId: '1',
    role: 'Junior Software Developer',
    company: 'TechCorp India',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=techcorp&backgroundColor=e6f3f3',
    status: 'Shortlisted',
    statusVariant: 'verified' as const,
    appliedDate: '20 Jul 2026',
    lastUpdate: '2 days ago',
    timeline: [
      { status: 'Applied', date: '20 Jul 2026', note: 'Your application was submitted', done: true },
      { status: 'Under Review', date: '22 Jul 2026', note: 'HR is reviewing applications', done: true },
      { status: 'Shortlisted', date: '24 Jul 2026', note: 'Great news — you\'ve been shortlisted!', done: true, active: true },
      { status: 'Interview', date: 'Pending', note: 'Interview invite coming soon', done: false },
      { status: 'Decision', date: '--', note: '', done: false },
    ],
  },
  {
    id: 'app-2',
    jobId: '2',
    role: 'Customer Support Associate',
    company: 'Zomato',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=zomato&backgroundColor=fef3e2',
    status: 'Under Review',
    statusVariant: 'pending' as const,
    appliedDate: '18 Jul 2026',
    lastUpdate: '4 days ago',
    timeline: [
      { status: 'Applied', date: '18 Jul 2026', note: 'Application submitted', done: true },
      { status: 'Under Review', date: '19 Jul 2026', note: 'Being reviewed by the team', done: true, active: true },
      { status: 'Interview', date: '--', note: '', done: false },
      { status: 'Decision', date: '--', note: '', done: false },
    ],
  },
  {
    id: 'app-3',
    jobId: '3',
    role: 'Graphic Designer',
    company: 'Ogilvy India',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=ogilvy&backgroundColor=f0fafa',
    status: 'Not selected',
    statusVariant: 'action' as const,
    appliedDate: '10 Jul 2026',
    lastUpdate: '10 days ago',
    timeline: [
      { status: 'Applied', date: '10 Jul 2026', note: 'Application submitted', done: true },
      { status: 'Reviewed', date: '12 Jul 2026', note: '', done: true },
      { status: 'Not selected', date: '16 Jul 2026', note: 'Not selected this time — they were looking for a more senior profile. Keep exploring similar roles!', done: true, active: true, rejected: true },
    ],
  },
];

export const PROVIDERS = [
  {
    id: 'p1',
    name: 'Dr. Ananya Krishnan',
    specialty: 'Physiotherapy',
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face',
    rating: 4.8,
    reviews: 124,
    location: 'Koramangala, Bengaluru',
    languages: ['Kannada', 'English', 'Hindi'],
    mode: ['In-person', 'Video'],
    nextSlot: 'Tomorrow, 10:00 AM',
    bio: 'Dr. Ananya specializes in rehabilitation for spinal cord injuries and post-stroke recovery. 12 years of experience with PwD patients.',
    accessibility: 'Fully accessible clinic — ramp access, lift, accessible examination table.',
  },
  {
    id: 'p2',
    name: 'Rahul Mehta',
    specialty: 'Counseling',
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop&crop=face',
    rating: 4.9,
    reviews: 87,
    location: 'Video only',
    languages: ['Hindi', 'English'],
    mode: ['Video'],
    nextSlot: 'Today, 4:00 PM',
    bio: 'Rahul provides counseling support for mental health and adjustment challenges related to disability and chronic illness. Specializes in CBT and acceptance therapy.',
    accessibility: 'Online sessions — no travel required. Sign language interpreter available.',
  },
  {
    id: 'p3',
    name: 'Dr. Meera Pillai',
    specialty: 'Speech Therapy',
    photo: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=150&h=150&fit=crop&crop=face',
    rating: 4.7,
    reviews: 56,
    location: 'Andheri West, Mumbai',
    languages: ['Malayalam', 'Hindi', 'English'],
    mode: ['In-person', 'Video'],
    nextSlot: 'Wed, 2:00 PM',
    bio: 'Speech and language pathologist with expertise in dysarthria, aphasia, and AAC device training.',
    accessibility: 'Ground floor clinic. AAC device consultation included.',
  },
];

export const SCHEMES = [
  {
    id: 's1',
    name: 'National Scholarship for PwD',
    ministry: 'Ministry of Social Justice & Empowerment',
    amount: '₹30,000 / year',
    description: 'Scholarship for students with disabilities enrolled in higher education. Covers tuition fees and living allowance.',
    eligibility: ['40%+ disability (UDID)', 'Annual family income < ₹2.5 lakh', 'Enrolled in Class 9 or above'],
    matchReason: 'Matches your disability category (Locomotor)',
    status: 'eligible',
    documentsRequired: ['UDID card', 'Income certificate', 'Enrollment letter', 'Bank account details'],
    applyLink: 'https://scholarships.gov.in',
  },
  {
    id: 's2',
    name: 'ADIP Scheme — Assistive Devices',
    ministry: 'ALIMCO / Ministry of SJE',
    amount: 'Free devices up to ₹10,000',
    description: 'Provides free or subsidised assistive devices — hearing aids, wheelchairs, white canes, prosthetics — to eligible PwD.',
    eligibility: ['40%+ disability', 'Monthly income < ₹15,000'],
    matchReason: 'Matches your disability category',
    status: 'applied',
    documentsRequired: ['UDID card', 'Medical prescription', 'Income certificate', 'Photo'],
    applyLink: 'https://alimco.in',
  },
  {
    id: 's3',
    name: 'Pradhan Mantri Employment Generation Programme',
    ministry: 'KVIC / Ministry of MSME',
    amount: 'Loan up to ₹25 lakh (for manufacturing)',
    description: 'Self-employment loan scheme with subsidies for persons with disabilities starting small businesses.',
    eligibility: ['Age 18+', 'Any disability type', 'Viable business plan'],
    matchReason: 'General eligibility — all PwD',
    status: 'eligible',
    documentsRequired: ['UDID card', 'Business plan', 'Aadhaar', 'Bank statement'],
    applyLink: 'https://kviconline.gov.in',
  },
];

export const COMMUNITY_POSTS = [
  {
    id: 'post1',
    author: 'Deepa R.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=60&h=60&fit=crop&crop=face',
    time: '2h ago',
    content: 'Just got shortlisted at Infosys through Sahay! For everyone applying to tech roles — the "Accessibility & accommodations" tab on job listings is a game changer. Don\'t hesitate to ask for what you need during interviews.',
    likes: 42,
    comments: 8,
    tag: 'Success story 🎉',
  },
  {
    id: 'post2',
    author: 'Vijay K.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop&crop=face',
    time: '5h ago',
    content: 'Question for the community: Does anyone have experience requesting a scribe for the UPSC exam? Looking for advice on the application timeline and documentation needed.',
    likes: 15,
    comments: 12,
    tag: 'Question',
  },
  {
    id: 'post3',
    author: 'Aruna S.',
    avatar: 'https://images.unsplash.com/photo-1601412436009-d964bd02edbc?w=60&h=60&fit=crop&crop=face',
    time: '1d ago',
    content: 'The ADIP scheme for assistive devices came through! Applied 3 weeks ago, hearing aids approved. The document vault on Sahay made it so easy to submit everything in one go.',
    likes: 67,
    comments: 5,
    tag: 'Benefits',
  },
];

export const MENTORS = [
  {
    id: 'm1',
    name: 'Karthik Subramanian',
    role: 'Senior Engineer at Google',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop&crop=face',
    tags: ['Tech careers', 'Low vision', 'Interview prep'],
    bio: 'Joined Google 4 years ago as a software engineer. Happy to share my experience navigating tech careers with low vision.',
  },
  {
    id: 'm2',
    name: 'Preethi Nair',
    role: 'HR Manager at Wipro',
    photo: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=120&h=120&fit=crop&crop=face',
    tags: ['HR & inclusion', 'Disability disclosure', 'Resume review'],
    bio: 'I help candidates understand how to navigate disability disclosure, accommodation requests, and inclusive hiring processes.',
  },
];
